### ISSUE TITLE
"Invalid" example on dry-system "Booting a dependency" page

### ISSUE THREAD

**Issue by francois** [dry-rb/dry-system#152]
**Describe the bug**

Copy-pasting the sample code on dry-system generates a TypeError when attempting to resolve a bootable dependency.

**To Reproduce**

### Reproduction recipe

```sh
git clone https://github.com/francois/bargo --branch repro && cd bargo && bundle exec ruby -e 'require "./system/container" ; Application[:logger]'
```

The [Auto-registration section on the Container page](https://dry-rb.org/gems/dry-system/master/container/#auto-registration) has the following sample application:

```ruby
# system/container.rb

require 'dry/system/container'

class Application < Dry::System::Container
  configure do |config|
    config.root = Pathname('./my/app')

    # we set 'lib' relative to `root` as a path which contains class definitions
    # that can be auto-registered
    config.auto_register = 'lib'
  end

  # this alters $LOAD_PATH hence the `!`
  load_paths!('lib')
end
```

[Booting a dependency](https://dry-rb.org/gems/dry-system/master/booting/) describes how to boot a 3rd party database system. I chose to go with the ubiquitous logger and transformed the original code into this:

```ruby
# system/boot/logger.rb

Application.boot(:logger) do
  init do
    require "logger"
  end

  start do
    logger = ::Logger.new(STDERR)
    logger.formatter = ->(timestamp, severity, appname, msg) do
      "[%-8.8s] [%6d] %-6.6s - %s\n" % [appname, Thread.current.object_id, severity, msg]
    end

    register(:logger, logger)
  end
end
```

I next started IRB and attempted to use the logger:

```
$ bundle exec irb
require_relative "system/container"
#=> true
Application[:logger]
```

The generated backtrace looks like:

```
Traceback (most recent call last):
       16: from /Users/francois/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
       15: from /Users/francois/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
       14: from /Users/francois/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
       13: from /Users/francois/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       12: from (irb):2
       11: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-container-0.7.2/lib/dry/container/mixin.rb:134:in `[]'
       10: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/container.rb:529:in `resolve'
        9: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/container.rb:639:in `load_component'
        8: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/container.rb:639:in `tap'
        7: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/container.rb:651:in `block in load_component'
        6: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/container.rb:691:in `load_local_component'
        5: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/booter.rb:120:in `boot_dependency'
        4: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/booter.rb:80:in `start'
        3: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/booter.rb:145:in `with_component'
        2: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/booter.rb:173:in `require_boot_file'
        1: from /Users/francois/.rvm/gems/ruby-2.6.5/gems/dry-system-0.18.1/lib/dry/system/booter.rb:173:in `require'
TypeError (no implicit conversion of Pathname into String)
```

I was able to work-around the problem by setting `config.root` to a String instead of a pathname:

```ruby
config.root = Pathname(".").realpath.to_s
```

See `system/container.rb` for the two lines.

**Expected behavior**

I expected to be able to copy-paste the sample code from dry-system and have a working system.

**Your environment**

- Ruby 2.6.5
- dry-system 0.18.1

**Comment by solnic** [comment]
Thanks for the report. I believe this is a bug (probably a regression) in the lib itself, not the docs.

**Comment by timriley** [comment]
I've just tested this with the following files:

system/container.rb:

```ruby
require "dry/system/container"

class Application < Dry::System::Container
  configure do |config|
    config.root = Pathname(__dir__).join("..")
    config.component_dirs.add "lib"
  end
end
```

system/providers/logger.rb:

```ruby
Application.register_provider(:logger) do
  init do
    require "logger"
  end

  start do
    logger = ::Logger.new(STDERR)
    logger.formatter = ->(timestamp, severity, appname, msg) do
      "[%-8.8s] [%6d] %-6.6s - %s\n" % [appname, Thread.current.object_id, severity, msg]
    end

    register(:logger, logger)
  end
end
```

And everything works fine when loading the logger in a `bundle exec irb` session:

```
irb(main):001:0" require_relative "system/container"
=> true
irb(main):002:1* Application[:logger]
[Dry::System::Provider::SourceDSL] Dry::System::Provider::SourceDSL#init is deprecated and will be removed in the next major version
Please use Dry::System::Provider::SourceDSL#prepare instead.
/Users/tim/Source/dry-rb/dry-system/examples/blah/system/providers/logger.rb:2:in `block in <top (required)>'
=> #<Logger:0x00007fd93b9109f8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007fd93b9109a8 @datetime_format=nil>, @formatter=#<Proc:0x00007fd93b910890 /Users/tim/Source/dry-rb/dry-system/examples/blah/system/providers/logger.rb:8 (lambda)>, @logdev=#<Logger::LogDevice:0x00007fd93b910958 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @binmode=false, @mon_data=#<Monitor:0x00007fd93b910930>, @mon_data_owner_object_id=1100>>
```

So I reckon it must have been a temporary glitch in some prior dry-system release. Things seem good now when a pathname is provided to `config.root=`.
