### ISSUE TITLE
LoadError cannot load such file -- rom

### ISSUE THREAD

**Issue by Hamada92** [dry-rb/dry-system#189]
Hello guys,

I'm trying to load `rom` in a boot file, but getting this error `LoadError cannot load such file -- rom`, here my boot file:

system/boot/persistence.rb:
```
Container.boot(:persistence) do
  init do
    require 'rom'
  end

  start do
    rom_config = ROM::Configuration.new(:sql, ENV['DATABASE_URL'])
    # rom_config.register_relation(Persistence::Relations::Questions)

    register("rom", ROM.container(rom_config))
  end
end
```

system/container.rb:

```
require 'dry/system/container'

class Container < Dry::System::Container
  configure do |config|
    config.name = :container
    config.component_dirs.add 'lib'
  end

end
```
from `irb`,
 `require './system/container'`
`Container.finalize!` # LoadError (cannot load such file -- rom)
`Container.start(:persistence)` # same error

Here's the full trace:

```
Traceback (most recent call last):
       16: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:178:in `with_component'
       15: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:87:in `block in init'
       14: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:125:in `call'
       13: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:178:in `with_component'
       12: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:128:in `block in call'
       11: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/booter.rb:88:in `block (2 levels) in init'
       10: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/components/bootable.rb:87:in `init'
        9: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:50:in `call'
        8: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:50:in `each'
        7: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:52:in `block in call'
        6: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:75:in `init'
        5: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:115:in `trigger!'
        4: from /Users/Ahmad/course_mate/system/boot/persistence.rb:3:in `block (2 levels) in <top (required)>'
        3: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:128:in `method_missing'
        2: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:128:in `public_send'
        1: from /Users/Ahmad/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/dry-system-0.19.2/lib/dry/system/lifecycle.rb:128:in `require'
LoadError (cannot load such file -- rom)
```
## Expected behavior

I expect the component to boot.

- Affects my production application: **NO**
- Ruby version: 2.7.0
- OS: BigSur

**Comment by flash-gordon** [comment]
pls show your Gemfile, something tells me you don't have rom there :)

**Comment by Hamada92** [comment]
@flash-gordon I do:

```
source "https://rubygems.org"

gem 'roda'
gem 'shotgun'
gem 'slim'
gem 'dry-view'
gem 'dry-system'
gem 'rom'
gem 'rom-sql'
gem 'pg'
gem 'dotenv'
gem "rake"
```

**Comment by flash-gordon** [comment]
Just a wild guess, does `bundle exec irb` change a thing?

**Comment by Hamada92** [comment]
@flash-gordon Yes, ver much working now. Any idea why that would be happening?

**Comment by flash-gordon** [comment]
well, it's about setting up bundler. You can do it manually with `require 'bundler/setup'`. It's the right way of using it. However, why `require 'rom'` works when typed explicitly and doesn't in the `init` block I honestly don't know :) I think most people just resort to `bundle exec` without giving too much thought to nuances, just as I do hah. Probably, reading the docs can clarify https://bundler.io/man/bundle-exec.1.html
Personally, I create custom shells for REPLs: see https://github.com/flash-gordon/rt-tracker/blob/main/bin/console and https://github.com/flash-gordon/rt-tracker/blob/f2c6f96c3e4eec7e1e5ecdb2b02733fe3cd2c2b1/Rakefile (just look at how pry is set up).

**Comment by Hamada92** [comment]
Thanks for unblocking me man.
