### ISSUE TITLE
cannot load such file -- dry/events/publisher (LoadError)

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-system#70]
dry-events seems to be required but not listed in the gemspec of the gem resulting in the following exception when booting my app:

```
/Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- dry/events/publisher (LoadError)
	from /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
	from /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/dry-system-0.9.0/lib/dry/system/plugins/monitoring.rb:3:in `<top (required)>'
```

on `require 'dry/system/container'` using `0.9.0`

**Comment by shanecav84** [comment]
I'm still getting this on `0.13.0`. Some plugins rely on `dry-events` but it's not listed in the gemspec. Should users install `dry-events` themselves?

```bash
irb(main):005:0> Dry::System::Plugins.registry[:monitoring].load_dependencies
Traceback (most recent call last):
        7: from bin/console:23:in `<main>'
        6: from <internal:prelude>:145:in `irb'
        5: from (irb):5:in `<main>'
        4: from .../dry-system-0.13.0/lib/dry/system/plugins.rb:32:in `load_dependencies'
        3: from .../dry-system-0.13.0/lib/dry/system/plugins.rb:32:in `each'
        2: from .../dry-system-0.13.0/lib/dry/system/plugins.rb:33:in `block in load_dependencies'
        1: from .../dry-system-0.13.0/lib/dry/system/plugins.rb:37:in `rescue in block in load_dependencies'
Dry::System::PluginDependencyMissing (dry-system plugin :monitoring failed to load its dependencies: cannot load such file -- dry/events/publisher)
```

**Comment by shanecav84** [comment]
`dry-monitor` is also required but not in the gemspec.

**Comment by solnic** [comment]
@shanecav84 these are not run-time dependencies. If you want to use a plugin that requires some additional gem, you need to add it to your Gemfile. What we could do to improve the situation is have a `gem_name => [list, of, requires]` so that we could provide a better exception message that would point you to the gem name that you gotta add to Gemfile. I reported #127 about it.
